// Stage 6 — BUILD. Emit the game map from the processed core, and finalize
// the manifest. Small maps become committed .ts modules; large maps become
// gzipped JSON assets (gitignored) served by the game server at /map.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { gzipSync } from "node:zlib";
import type { GameMap } from "@battle-juice/shared";
import { MANIFEST_FILE, MAP_NAME, MAP_OUT_FILE, MAPS_ASSET_DIR, processedDir } from "./config.js";
import { bakeLandmarks } from "./landmarks.js";

const TS_MODULE_LIMIT = 8 * 1024 * 1024; // beyond this, bake as a gz asset

const coreFile = join(processedDir(), `${MAP_NAME}-core.json`);
const map = JSON.parse(readFileSync(coreFile, "utf8")) as GameMap;

// Landmarks join here (separate source from the ArcGIS core) — reprojected
// and clipped to the same play area.
const marks = bakeLandmarks(map.meta.width, map.meta.height, map.buildings);
map.landmarks = marks.landmarks;
console.log(
  `landmarks: ${marks.landmarks.length} in play area` +
    (marks.outside ? ` (${marks.outside} outside, dropped)` : "") +
    `, ${marks.landmarks.length - marks.unmatched.length} matched to a building` +
    (marks.unmatched.length ? ` (no footprint: ${marks.unmatched.join(", ")})` : "") +
    (marks.suspicious.length ? ` (cluster under 250 m², verify: ${marks.suspicious.join(", ")})` : "") +
    (marks.source ? ` — ${marks.source}` : " — none (data/landmarks.json missing)"),
);

const json = JSON.stringify(map);

let outDesc: string;
let outFile: string;
if (json.length <= TS_MODULE_LIMIT) {
  const header =
    "// GENERATED by tools/map-extract — do not edit by hand.\n" +
    `// Source: City of Portland open data, extracted ${map.meta.sourceDate}. See data/MANIFEST.json.\n` +
    'import type { GameMap } from "../map.js";\n\n';
  // JSON.parse of a string literal: a plain object literal this large trips
  // TS2590 (union too complex) on the props array.
  writeFileSync(MAP_OUT_FILE, header + `export const ${MAP_NAME}Map = JSON.parse(${JSON.stringify(json)}) as GameMap;\n`);
  outDesc = "ts-module";
  outFile = MAP_OUT_FILE;
} else {
  mkdirSync(MAPS_ASSET_DIR, { recursive: true });
  outFile = join(MAPS_ASSET_DIR, `${MAP_NAME}.json.gz`);
  const gz = gzipSync(json, { level: 9 });
  writeFileSync(outFile, gz);
  outDesc = `gz-asset (${(json.length / 1048576).toFixed(1)} MB raw, ${(gz.length / 1048576).toFixed(1)} MB gz)`;
}

const manifest = JSON.parse(readFileSync(MANIFEST_FILE, "utf8")) as Record<string, unknown>;
manifest["bakedMap"] = {
  file: outFile.includes("data/") ? `data/maps/${MAP_NAME}.json.gz` : `shared/src/maps/${MAP_NAME}.ts`,
  kind: outDesc,
  meta: map.meta,
  nodes: map.nodes.length,
  edges: map.edges.length,
  buildings: map.buildings.length,
  props: map.props.length,
  water: map.water?.length ?? 0,
  landmarks: {
    count: marks.landmarks.length,
    matchedToBuilding: marks.landmarks.length - marks.unmatched.length,
    source: marks.source,
    scrapedAt: marks.scrapedAt,
  },
};
writeFileSync(MANIFEST_FILE, JSON.stringify(manifest, null, 2) + "\n");

console.log(
  `baked ${outFile} [${outDesc}]\n` +
    `  ${map.meta.width}x${map.meta.height} m | nodes ${map.nodes.length} | edges ${map.edges.length} | ` +
    `buildings ${map.buildings.length} | props ${map.props.length} | water ${map.water?.length ?? 0} | ` +
    `landmarks ${map.landmarks.length} | ` +
    `entries N=${map.entries.north.length} S=${map.entries.south.length}`,
);
