// Stage 6 — BUILD. Emit the committed game map module from the processed
// core, and finalize the manifest.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { GameMap } from "@battle-juice/shared";
import { MANIFEST_FILE, MAP_NAME, MAP_OUT_FILE, processedDir } from "./config.js";

const coreFile = join(processedDir(), `${MAP_NAME}-core.json`);
const map = JSON.parse(readFileSync(coreFile, "utf8")) as GameMap;

const exportName = `${MAP_NAME}Map`;
const header =
  "// GENERATED by tools/map-extract — do not edit by hand.\n" +
  `// Source: City of Portland open data, extracted ${map.meta.sourceDate}. See data/MANIFEST.json.\n` +
  'import type { GameMap } from "../map.js";\n\n';
// JSON.parse of a string literal: a plain object literal this large trips
// TS2590 (union too complex) on the props array.
writeFileSync(
  MAP_OUT_FILE,
  header + `export const ${exportName} = JSON.parse(${JSON.stringify(JSON.stringify(map))}) as GameMap;\n`,
);

const manifest = JSON.parse(readFileSync(MANIFEST_FILE, "utf8")) as Record<string, unknown>;
manifest["bakedMap"] = {
  file: `shared/src/maps/${MAP_NAME}.ts`,
  meta: map.meta,
  nodes: map.nodes.length,
  edges: map.edges.length,
  buildings: map.buildings.length,
  props: map.props.length,
  water: map.water?.length ?? 0,
};
writeFileSync(MANIFEST_FILE, JSON.stringify(manifest, null, 2) + "\n");

console.log(
  `baked ${MAP_OUT_FILE}\n` +
    `  ${map.meta.width}x${map.meta.height} m | nodes ${map.nodes.length} | edges ${map.edges.length} | ` +
    `buildings ${map.buildings.length} | props ${map.props.length} | water ${map.water?.length ?? 0} | ` +
    `entries N=${map.entries.north.length} S=${map.entries.south.length}`,
);
