// Stage 6 — BUILD. Emit the game map from the processed core, and finalize
// the manifest. Small maps become committed .ts modules; large maps become
// gzipped JSON assets (gitignored) served by the game server at /map.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { gzipSync } from "node:zlib";
import type { GameMap } from "@battle-juice/shared";
import { MANIFEST_FILE, MAP_NAME, MAP_OUT_FILE, MAPS_ASSET_DIR, processedDir } from "./config.js";

const TS_MODULE_LIMIT = 8 * 1024 * 1024; // beyond this, bake as a gz asset

const coreFile = join(processedDir(), `${MAP_NAME}-core.json`);
const json = readFileSync(coreFile, "utf8");
const map = JSON.parse(json) as GameMap;

let outDesc: string;
let outFile: string;
if (json.length <= TS_MODULE_LIMIT) {
  const header =
    "// GENERATED by tools/map-extract — do not edit by hand.\n" +
    `// Source: City of Portland open data, extracted ${map.meta.sourceDate}. See data/MANIFEST.json.\n` +
    'import type { GameMap } from "../map.js";\n\n';
  // JSON.parse of a string literal: a plain object literal this large trips
  // TS2590 (union too complex) on the props array.
  writeFileSync(MAP_OUT_FILE, header + `export const ${MAP_NAME}Map = JSON.parse(${JSON.stringify(json)}) as GameMap;\n`);
  outDesc = "ts-module";
  outFile = MAP_OUT_FILE;
} else {
  mkdirSync(MAPS_ASSET_DIR, { recursive: true });
  outFile = join(MAPS_ASSET_DIR, `${MAP_NAME}.json.gz`);
  const gz = gzipSync(json, { level: 9 });
  writeFileSync(outFile, gz);
  outDesc = `gz-asset (${(json.length / 1048576).toFixed(1)} MB raw, ${(gz.length / 1048576).toFixed(1)} MB gz)`;
}

const manifest = JSON.parse(readFileSync(MANIFEST_FILE, "utf8")) as Record<string, unknown>;
manifest["bakedMap"] = {
  file: outFile.includes("data/") ? `data/maps/${MAP_NAME}.json.gz` : `shared/src/maps/${MAP_NAME}.ts`,
  kind: outDesc,
  meta: map.meta,
  nodes: map.nodes.length,
  edges: map.edges.length,
  buildings: map.buildings.length,
  props: map.props.length,
  water: map.water?.length ?? 0,
};
writeFileSync(MANIFEST_FILE, JSON.stringify(manifest, null, 2) + "\n");

console.log(
  `baked ${outFile} [${outDesc}]\n` +
    `  ${map.meta.width}x${map.meta.height} m | nodes ${map.nodes.length} | edges ${map.edges.length} | ` +
    `buildings ${map.buildings.length} | props ${map.props.length} | water ${map.water?.length ?? 0} | ` +
    `entries N=${map.entries.north.length} S=${map.entries.south.length}`,
);
